# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d77ffc8b1d7472d657dd9f75c949b13d8d4a348762b5f49a886c2249b464bdefdb6c7fed8b8f30845bb9fa0cfe0d461adc8d5e1ded7c048e5926e75d58668bf1

test:
  secret_key_base: 5ef257abb8112846e457c4161d856226fe0628d9da85c5bfb6ec6ff4e6cdb4b4403a165064f0c51a4b7cdde2f745c7bd39eabdd73c9beafc86d6ce76458e889e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
